### ISSUE TITLE
CouchDB Get method doesn't return value for the key that is an URL

### ISSUE THREAD

**Issue by aholovko** [trustbloc/edge-core#127]
`Put` with URL as a key works fine.

To reproduce save some data using, for example, "https://kms.example.com:8076/kms/keystores/bv7ba41340d979mp7sag" as a key and then try to get stored data back.

**Comment by DRK3** [comment]
Issue happens with new Kivik version that I had to update to since the old one didn't work for bulk put

```
github.com/go-kivik/couchdb/v3 v3.2.5
github.com/go-kivik/kivik/v3 v3.2.3
```

^^Something there causes an issue for strings with certain characters in them.

```
github.com/go-kivik/couchdb v2.0.0+incompatible
github.com/go-kivik/kivik v2.0.0+incompatible
```

^^ doesn't have this bug

**Comment by DRK3** [comment]
#143 closed this

**Comment by DRK3** [comment]
(The successor to this storage implementation at https://github.com/hyperledger/aries-framework-go-ext/tree/main/component/storage/couchdb fixes this issue)
