### ISSUE TITLE
Guard against sql injection:

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/edge-core#38]
I believe there's an SQL injection attack possibility here that needs to be addressed...unless this is somehow handled by the underlying library already. I found an article here that looks helpful: https://www.calhoun.io/what-is-sql-injection-and-how-do-i-avoid-it-in-go/

^ It describes how to avoid injection attacks via escaping (so you can still have your parameterized table name). Not sure if they're using the same library as you, but I assume there should be an equivalent if your library is different

https://github.com/trustbloc/edge-core/pull/37#discussion_r450338088

**Comment by DRK3** [comment]
Appears to have been closed by accident
